### ISSUE TITLE
Move equib routines to externals directory

### ISSUE THREAD

**Issue by mdpiper** [equib/proEQUIB#5]
The `equib_*` routines in the `pro` directory appear to be written by others. To separate them from the work of @danehkar, I'd suggest that they be moved to a new directory under `externals`.

**Comment by danehkar** [comment]
I selected these routines (interp2d.pro, meshgrid.pro, sign.pro, str2int.pro, strnumber.pro) from other IDL libraries to replace some FORTRAN functions of [EQUIB](https://github.com/equib/EQUIB) during the conversion from FORTRAN to IDL. I added `equib_*` to them to separate from other IDL functions with similar names in other IDL packages in my machine. Now I changed  `equib_*` to `_*` and moved them to to a`misc` under `externals`.
